# ... your existing imports ...

def load_and_plot(results_file):
    # Load results including 'date' column
    # ... existing data loading ...
    # Visualize results as before
    # If desired, add a plot showing results by 'date'
    # ... existing plotting code ...